name: Build & Deploy DJ Simblue
on:
  push:
    branches: [dist]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build 🔧
        run: |
          yarn install
          yarn deploy-storybook -- --ci --host-token-env-variable=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
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
